spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/interview-project-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    generate-ddl: true
    show-sql: false